kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test

- name: docker
  image: plugins/docker
  settings:
    repo: syhlion/gusher.cluster
    dockerfile: docker/Dockerfile
    auto_tag: true
    purge: true
    username:
        from_secret: docker_account
    password:
        from_secret: docker_password
- name: build
  image: golang
  commands:
  - git fetch --tags
  - make build/linux_amd64.tar.gz
  - make build/darwin_amd64.tar.gz
  - make build/windows_amd64.tar.gz
  when:
    event: tag
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: build/*
    checksum:
        - md5
    title: ${DRONE_TAG}
    note: CHANGELOG.md
    draft: true
  when:
    event: tag
- name: notify
  image: appleboy/drone-telegram
  settings:
    message: >
        {{#success build.status}}
            {{repo.namespace}}/{{repo.name}} build {{build.number}}. commit {{commit.sha}} succeeded. Good job.
            {{else}}
            {{repo.namespace}}/{{repo.name}} build {{build.number}}. commit {{commit.sha}} failed. Fix me please.
        {{/success}}
    token:
        from_secret: bot_token
    to:
        from_secret: bot_to
  when:
    status:
    - failure
    - success
